### PR TITLE
Feature/maintenance

### PR DESCRIPTION
**Pull request by ghost**
### Context
https://enrise.atlassian.net/browse/SAAS-1008

### What has been done
- Update dependencies
- Add note about ajv and chai-json-schema-ajv to the readme
- Remove people from maintainer list that no longer want to be a maintainer

### How to test
- Check the travis builds still work 
- Use the new version in our tests

### Todo
- [x] Upgrade the version number

### Notes
- I saw we don't use a `package-lock.json` in this repo. This is probably okay since this is intended a package but it feels a bit weird.

### CODE REVIEW

**Comment by keithamus** [comment]
FWIW if you, or @up9cloud or anyone else wants to pick up maintenance of this module and move it to using `ajv` I'd happily set you up to do so. More-so if anyone wants to merge the efforts of `chai-json-schema-ajv` into this I'd be happy to also do that.

There is no resistance to using `ajv` over `tv4` - it is just we're very limited on maintainer-ship. If people are happy to work on this project, I'm more than happy to hand the keys over 😄

**Comment by edwardsmit** [comment]
Thank you for your feedback @keithamus 
We definitely also support efforts for merging the two, but haven't got the time, nor the project-driven motivation for such.
That said we will try to keep this plugin at the level where it is, and welcome any PR's.

**Review by edwardsmit — APPROVED** [review]

**Comment by sbeekhuis** [comment]
Since I have no offical role/permissions in this repo I can't merge this merge request. @edwardsmit please merge. :)

**Comment by sbeekhuis** [comment]
I forgot to version a new version. Now I did :/

**Pull request merged**
