### PR TITLE
Delete MAINTAINERS

### PR DESCRIPTION
**Pull request by keithamus**
### What has been done
-

### How to test
-

### Todo
- [ ]

### Notes
-

### CODE REVIEW

**Comment by thabemmz** [comment]
Hi @keithamus. Why would you remove this file?

**Comment by keithamus** [comment]
Hi @thabemmz, sorry should have added a description.

LGTM is no longer available as a service, so this file is effectively useless. Maintainers are managed via the Chai Teams (https://github.com/orgs/chaijs/teams/chai-json-schema).

**Comment by edwardsmit** [comment]
@keithamus Link returns 404

**Comment by JrSchild** [comment]
That page is only accessible for users within the Chai organization, not within the Enrise org. I think that's okay, since all necessary members of my team have sufficient commit access.

**Comment by edwardsmit** [comment]
@keithamus I don't see any harm in having this file in the repository. We'll keep it.

**Pull request closed without merging**
