### PR TITLE
Add multiple option

### PR DESCRIPTION
**Pull request by Niklv**
ref #36

### CODE REVIEW

**Comment by JrSchild** [comment]
Hi @Niklv 
- Can you add a space after `if` in `if(chai.tv4.multiple) {`?
- Could you add some test cases for functionality?

For the rest this functionality is good.

**Comment by Niklv** [comment]
@JrSchild Hi, any progress with this PR?

**Comment by thabemmz** [comment]
lgtm

**Comment by JrSchild** [comment]
Thanks @thabemmz. This will be included in the next minor release.

**Pull request merged**
