### PR TITLE
Updating Chai to 2.2.x and removing nodeJS 0.8 support

### PR DESCRIPTION
**Pull request by trickeyone**
I've ran the tests using Travis-CI. Build successful and passing.
https://travis-ci.org/trickeyone/chai-json-schema/builds/58359210

### CODE REVIEW

**Comment by lpaulger** [comment]
+1 for this to be merged

**Comment by PaulThompson** [comment]
Master has been updated with PR #16 
Can you check the new conflicts in context of latest master?
I'd suggest rebase ahead of master.

**Comment by googoid** [comment]
is it going to be merged?

**Comment by PaulThompson** [comment]
The change looks OK but master has been updated with PR #16, so there are conflicts in context of latest master.  I'd suggest rebase ahead of master.

**Comment by JrSchild** [comment]
I have manually merged your code to resolve conflicts. Thank you.

**Pull request closed without merging**
